// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/grachmannico95/mileapp-test-be/internal/model"
	mock "github.com/stretchr/testify/mock"

	primitive "go.mongodb.org/mongo-driver/bson/primitive"

	repository "github.com/grachmannico95/mileapp-test-be/internal/repository"
)

// MockTaskRepository is an autogenerated mock type for the TaskRepository type
type MockTaskRepository struct {
	mock.Mock
}

type MockTaskRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskRepository) EXPECT() *MockTaskRepository_Expecter {
	return &MockTaskRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, task
func (_m *MockTaskRepository) Create(ctx context.Context, task *model.Task) error {
	ret := _m.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Task) error); ok {
		r0 = rf(ctx, task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTaskRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - task *model.Task
func (_e *MockTaskRepository_Expecter) Create(ctx interface{}, task interface{}) *MockTaskRepository_Create_Call {
	return &MockTaskRepository_Create_Call{Call: _e.mock.On("Create", ctx, task)}
}

func (_c *MockTaskRepository_Create_Call) Run(run func(ctx context.Context, task *model.Task)) *MockTaskRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Task))
	})
	return _c
}

func (_c *MockTaskRepository_Create_Call) Return(_a0 error) *MockTaskRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskRepository_Create_Call) RunAndReturn(run func(context.Context, *model.Task) error) *MockTaskRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockTaskRepository) Delete(ctx context.Context, id primitive.ObjectID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTaskRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id primitive.ObjectID
func (_e *MockTaskRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockTaskRepository_Delete_Call {
	return &MockTaskRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockTaskRepository_Delete_Call) Run(run func(ctx context.Context, id primitive.ObjectID)) *MockTaskRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(primitive.ObjectID))
	})
	return _c
}

func (_c *MockTaskRepository_Delete_Call) Return(_a0 error) *MockTaskRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskRepository_Delete_Call) RunAndReturn(run func(context.Context, primitive.ObjectID) error) *MockTaskRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function with given fields: ctx, filters
func (_m *MockTaskRepository) Find(ctx context.Context, filters repository.TaskFilters) ([]model.Task, int64, error) {
	ret := _m.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 []model.Task
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.TaskFilters) ([]model.Task, int64, error)); ok {
		return rf(ctx, filters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.TaskFilters) []model.Task); ok {
		r0 = rf(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.TaskFilters) int64); ok {
		r1 = rf(ctx, filters)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, repository.TaskFilters) error); ok {
		r2 = rf(ctx, filters)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockTaskRepository_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockTaskRepository_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - filters repository.TaskFilters
func (_e *MockTaskRepository_Expecter) Find(ctx interface{}, filters interface{}) *MockTaskRepository_Find_Call {
	return &MockTaskRepository_Find_Call{Call: _e.mock.On("Find", ctx, filters)}
}

func (_c *MockTaskRepository_Find_Call) Run(run func(ctx context.Context, filters repository.TaskFilters)) *MockTaskRepository_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.TaskFilters))
	})
	return _c
}

func (_c *MockTaskRepository_Find_Call) Return(_a0 []model.Task, _a1 int64, _a2 error) *MockTaskRepository_Find_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockTaskRepository_Find_Call) RunAndReturn(run func(context.Context, repository.TaskFilters) ([]model.Task, int64, error)) *MockTaskRepository_Find_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockTaskRepository) FindByID(ctx context.Context, id primitive.ObjectID) (*model.Task, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) (*model.Task, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) *model.Task); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockTaskRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id primitive.ObjectID
func (_e *MockTaskRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockTaskRepository_FindByID_Call {
	return &MockTaskRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockTaskRepository_FindByID_Call) Run(run func(ctx context.Context, id primitive.ObjectID)) *MockTaskRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(primitive.ObjectID))
	})
	return _c
}

func (_c *MockTaskRepository_FindByID_Call) Return(_a0 *model.Task, _a1 error) *MockTaskRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskRepository_FindByID_Call) RunAndReturn(run func(context.Context, primitive.ObjectID) (*model.Task, error)) *MockTaskRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, task
func (_m *MockTaskRepository) Update(ctx context.Context, task *model.Task) error {
	ret := _m.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Task) error); ok {
		r0 = rf(ctx, task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTaskRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - task *model.Task
func (_e *MockTaskRepository_Expecter) Update(ctx interface{}, task interface{}) *MockTaskRepository_Update_Call {
	return &MockTaskRepository_Update_Call{Call: _e.mock.On("Update", ctx, task)}
}

func (_c *MockTaskRepository_Update_Call) Run(run func(ctx context.Context, task *model.Task)) *MockTaskRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Task))
	})
	return _c
}

func (_c *MockTaskRepository_Update_Call) Return(_a0 error) *MockTaskRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskRepository_Update_Call) RunAndReturn(run func(context.Context, *model.Task) error) *MockTaskRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTaskRepository creates a new instance of MockTaskRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskRepository {
	mock := &MockTaskRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
