// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/grachmannico95/mileapp-test-be/internal/dto"
	mock "github.com/stretchr/testify/mock"

	model "github.com/grachmannico95/mileapp-test-be/internal/model"
)

// MockTaskService is an autogenerated mock type for the TaskService type
type MockTaskService struct {
	mock.Mock
}

type MockTaskService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskService) EXPECT() *MockTaskService_Expecter {
	return &MockTaskService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, req
func (_m *MockTaskService) Create(ctx context.Context, req dto.CreateTaskRequest) (*model.Task, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateTaskRequest) (*model.Task, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateTaskRequest) *model.Task); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.CreateTaskRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTaskService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - req dto.CreateTaskRequest
func (_e *MockTaskService_Expecter) Create(ctx interface{}, req interface{}) *MockTaskService_Create_Call {
	return &MockTaskService_Create_Call{Call: _e.mock.On("Create", ctx, req)}
}

func (_c *MockTaskService_Create_Call) Run(run func(ctx context.Context, req dto.CreateTaskRequest)) *MockTaskService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.CreateTaskRequest))
	})
	return _c
}

func (_c *MockTaskService_Create_Call) Return(_a0 *model.Task, _a1 error) *MockTaskService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskService_Create_Call) RunAndReturn(run func(context.Context, dto.CreateTaskRequest) (*model.Task, error)) *MockTaskService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockTaskService) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTaskService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockTaskService_Expecter) Delete(ctx interface{}, id interface{}) *MockTaskService_Delete_Call {
	return &MockTaskService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockTaskService_Delete_Call) Run(run func(ctx context.Context, id string)) *MockTaskService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTaskService_Delete_Call) Return(_a0 error) *MockTaskService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskService_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockTaskService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockTaskService) GetByID(ctx context.Context, id string) (*model.Task, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Task, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Task); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockTaskService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockTaskService_Expecter) GetByID(ctx interface{}, id interface{}) *MockTaskService_GetByID_Call {
	return &MockTaskService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockTaskService_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockTaskService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTaskService_GetByID_Call) Return(_a0 *model.Task, _a1 error) *MockTaskService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskService_GetByID_Call) RunAndReturn(run func(context.Context, string) (*model.Task, error)) *MockTaskService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, params
func (_m *MockTaskService) List(ctx context.Context, params dto.TaskQueryParams) ([]model.Task, dto.PaginationMeta, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.Task
	var r1 dto.PaginationMeta
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.TaskQueryParams) ([]model.Task, dto.PaginationMeta, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.TaskQueryParams) []model.Task); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.TaskQueryParams) dto.PaginationMeta); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Get(1).(dto.PaginationMeta)
	}

	if rf, ok := ret.Get(2).(func(context.Context, dto.TaskQueryParams) error); ok {
		r2 = rf(ctx, params)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockTaskService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockTaskService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - params dto.TaskQueryParams
func (_e *MockTaskService_Expecter) List(ctx interface{}, params interface{}) *MockTaskService_List_Call {
	return &MockTaskService_List_Call{Call: _e.mock.On("List", ctx, params)}
}

func (_c *MockTaskService_List_Call) Run(run func(ctx context.Context, params dto.TaskQueryParams)) *MockTaskService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.TaskQueryParams))
	})
	return _c
}

func (_c *MockTaskService_List_Call) Return(_a0 []model.Task, _a1 dto.PaginationMeta, _a2 error) *MockTaskService_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockTaskService_List_Call) RunAndReturn(run func(context.Context, dto.TaskQueryParams) ([]model.Task, dto.PaginationMeta, error)) *MockTaskService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, req
func (_m *MockTaskService) Update(ctx context.Context, id string, req dto.UpdateTaskRequest) (*model.Task, error) {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, dto.UpdateTaskRequest) (*model.Task, error)); ok {
		return rf(ctx, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, dto.UpdateTaskRequest) *model.Task); ok {
		r0 = rf(ctx, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, dto.UpdateTaskRequest) error); ok {
		r1 = rf(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTaskService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - req dto.UpdateTaskRequest
func (_e *MockTaskService_Expecter) Update(ctx interface{}, id interface{}, req interface{}) *MockTaskService_Update_Call {
	return &MockTaskService_Update_Call{Call: _e.mock.On("Update", ctx, id, req)}
}

func (_c *MockTaskService_Update_Call) Run(run func(ctx context.Context, id string, req dto.UpdateTaskRequest)) *MockTaskService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(dto.UpdateTaskRequest))
	})
	return _c
}

func (_c *MockTaskService_Update_Call) Return(_a0 *model.Task, _a1 error) *MockTaskService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskService_Update_Call) RunAndReturn(run func(context.Context, string, dto.UpdateTaskRequest) (*model.Task, error)) *MockTaskService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTaskService creates a new instance of MockTaskService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskService {
	mock := &MockTaskService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
